### ISSUE TITLE
Stream Notifier

### ISSUE THREAD

**Issue by dmurphy95** [ciarancrocker/sgs_bot#16]
Possible inclusion of the bot posting a message onto a channel regarding a livestream going online, primarily Twitch focused.

Ideally editable with a admin command.

**Comment by ciarancrocker** [comment]
So this is something that can be done, but it's a bit clunky due to Twitch not providing a method to subscribe to channel events. The janky way of doing it would be to check the Twitch channel's broadcast status every so often (say every 5 minutes?) in a `setInterval`. It won't be instantaneous, but it'll work.

As for configuration, this sounds like something that can just live in the database for the time being, though I'd like to say we need to move to a migrations model so people can keep up with the bot properly rather than having to pick and choose snippets of SQL to run whenever the schema changes.

**Comment by ciarancrocker** [comment]
Due to a lack of interest in this I'm closing it out. Feel free to request reopening if this is something you can contribute.
